name: SonarCloud Scanner v2

# Trigger analysis when pushing in development/master or pull requests, and when creating
# a pull request.

on:
  push:
    branches:
      - "master"
      - "development"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
