name: SonarCloud Scan

# Trigger analysis when pushing in development/master or pull requests, and when creating
# a pull request.

on:
  push:
    branches:
      - "main"
      - "master"
      - "development"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: "5832b4992c00aa34170bae3bb0a2aa5f34157113"
          SONAR_TOKEN: "5db4686a59de16726619220f86460d2a97cc1306"
