name: SonarCloud Scanner

# Trigger analysis when pushing/merging into development/master
on:
  push:
    branches:
      - "main"
      - "master"
      - "development"

jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install modules
        run: yarn
      - name: Run tests and create coverage report
        run: yarn test -- --coverage
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
